set(
    BENCHMARK_SOURCES
    abstract_benchmark_config.hpp
    abstract_benchmark_result.hpp
    abstract_benchmark_runner.hpp
    abstract_benchmark.hpp
    benchmark_helper.cpp
    benchmark_helper.hpp
    benchmark_result_aggregate.cpp
    benchmark_result_aggregate.hpp
    compression/compressor.cpp
    compression/compressor.hpp
    compression/decompressor.cpp
    compression/decompressor.hpp
    compression/processor.cpp
    compression/processor.hpp
    data_generation/abstract_generator.hpp
    data_generation/table_builder.hpp
    data_generation/tpch/tpch_generator.hpp
    data_generation/tpch/tpch_generator.cpp
    ec2/ec2_benchmark_config.cpp
    ec2/ec2_benchmark_config.hpp
    ec2/ec2_benchmark_result.cpp
    ec2/ec2_benchmark_result.hpp
    ec2/ec2_benchmark_runner.cpp
    ec2/ec2_benchmark_runner.hpp
    ec2/ec2_invocation_benchmark.cpp
    ec2/ec2_invocation_benchmark.hpp
    lambda/function_colocation_benchmark.cpp
    lambda/function_colocation_benchmark.hpp
    lambda/function_invocation_config.hpp
    lambda/function_warm_up_benchmark.cpp
    lambda/function_warm_up_benchmark.hpp
    lambda/function_warm_up_continuous_benchmark.cpp
    lambda/function_warm_up_continuous_benchmark.hpp
    lambda/idle_availability_benchmark.cpp
    lambda/idle_availability_benchmark.hpp
    lambda/idle_lifetime_benchmark.cpp
    lambda/idle_lifetime_benchmark.hpp
    lambda/invocation_latency_benchmark.hpp
    lambda/invocation_latency_benchmark.cpp
    lambda/invocation_throughput_benchmark.cpp
    lambda/invocation_throughput_benchmark.hpp
    lambda/lambda_benchmark_config.cpp
    lambda/lambda_benchmark_config.hpp
    lambda/lambda_benchmark_output.cpp
    lambda/lambda_benchmark_output.hpp
    lambda/lambda_benchmark_result.cpp
    lambda/lambda_benchmark_result.hpp
    lambda/lambda_benchmark_runner.cpp
    lambda/lambda_benchmark_runner.hpp
    lambda/lambda_benchmark.cpp
    lambda/lambda_benchmark.hpp
    lambda/log_result.cpp
    lambda/log_result.hpp
    lambda/network_benchmark.cpp
    lambda/network_benchmark.hpp
    lambda/network_latency_benchmark.cpp
    lambda/network_latency_benchmark.hpp
    lambda/network_throughput_benchmark.cpp
    lambda/network_throughput_benchmark.hpp
    lambda/network_throughput_parallel_benchmark.cpp
    lambda/network_throughput_parallel_benchmark.hpp
)

set(
    BENCHMARK_LIBRARIES
    aws-cpp-sdk-core
    aws-cpp-sdk-ec2
    aws-cpp-sdk-iam
    aws-cpp-sdk-lambda
    aws-cpp-sdk-s3
    aws-cpp-sdk-sqs
    aws-cpp-sdk-xray
    gtest_main
    tpch-dbgen

    skyriseShared
)

add_library(skyriseBenchmark STATIC ${BENCHMARK_SOURCES})

target_include_directories(
    skyriseBenchmark

    PRIVATE
    ${CMAKE_BINARY_DIR}/third_party/orc/c++/src
    ${CMAKE_BINARY_DIR}/third_party/orc/protobuf_ep-prefix/src/protobuf_ep/src
    ${PROJECT_SOURCE_DIR}/third_party/orc/c++/src
)

target_link_libraries(
    skyriseBenchmark
    INTERFACE
    skyriseCoordinator
    PUBLIC
    ${BENCHMARK_LIBRARIES}
)
