name: deploy-lambda-functions-arm
on:
  # Weekly schedule for Sundays at 21:59 UTC.
  schedule:
    - cron: '59 21 * * 0'
  workflow_dispatch:
    inputs:
      # Name of the target function without 'aws-lambda-package-' prefix.
      function_name:
        description: 'Function Name'
        required: true
        default: 'skyriseFunctionReadS3'
      # Specify the memory configuration of the function.
      memory_configuration:
        type: choice
        description: 'Memory Allocation'
        required: false
        default: '128'
        options:
          - '128'
          - '1024'
          - '2048'
          - '4096'
          - '10240'
      # Specify the build type (Release or Debug) of the function.
      build_type:
        type: choice
        description: 'Build Type'
        required: true
        default: 'Release'
        options:
          - 'Release'
          - 'Debug'
      # Description, uses the GitHub username if not explicitly provided.
      description:
        description: 'Description'
        required: true
        default: GitHub Username

env:
  FUNCTION_NAME: ${{ inputs.function_name }}
  MEMORY_CONFIGURATION: ${{ inputs.memory_configuration }}
  BUILD_TYPE: ${{ inputs.build_type }}
  DESCRIPTION: ${{ inputs.description }}

jobs:
  # Start the Amazon EC2 CI runner.
  start-ec2-instance:
    runs-on: [ self-hosted, amazonlinux2 ]
    name: Start Amazon EC2 Instance
    steps:
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

  # Build the target function on the Amazon EC2 runner and upload it.
  build-arm-function:
    runs-on: [ self-hosted, ARM64, deploy ]
    name: Build and upload function
    needs: start-ec2-instance
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Set the environment variables for a scheduled run.
      - name: Configure Scheduled Run
        if: github.event_name == 'schedule'
        run: |
          echo "FUNCTION_NAME=skyriseFunctionReadS3" >> $GITHUB_ENV
          echo "MEMORY_CONFIGURATION=128" >> $GITHUB_ENV
          echo "BUILD_TYPE=Release" >> $GITHUB_ENV
          echo "DESCRIPTION=skyrise-ci" >> $GITHUB_ENV    

      - name: Set Description
        run: |
          if [ '${{ env.DESCRIPTION }}' = 'GitHub Username' ]; then echo "DESCRIPTION=${{ github.actor }}" >> $GITHUB_ENV; \
          else echo "DESCRIPTION=${{ env.DESCRIPTION }}" >> $GITHUB_ENV; fi;    

      - name: "CMake Configure"
        run: |
          mkdir cmake-build
          cd cmake-build
          cmake .. -GNinja \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DSKYRISE_BUILD_GRAVITON2=ON \
            -DSKYRISE_ENABLE_CCACHE=OFF \

      - name: "Build ${{ env.FUNCTION_NAME }}"
        run: |
          cd cmake-build
          ninja-build aws-lambda-package-${{ env.FUNCTION_NAME }} skyrise -j$(nproc)

      - name: "Upload ${{ env.FUNCTION_NAME }} to AWS"
        run: |
          cd cmake-build
          ./bin/skyrise -t function-upload -n ${{ env.FUNCTION_NAME }} -d ${{ env.DESCRIPTION}} -m ${{ env.MEMORY_CONFIGURATION }}

  # Stop the Amazon EC2 instance.
  stop-ec2-instance:
    runs-on: [ self-hosted, amazonlinux2 ]
    name: Stop Amazon EC2 Instance
    if: always()
    needs: [ start-ec2-instance, build-arm-function ]
    steps:
      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
