name: deploy-lambda-functions-arm
on:
  workflow_dispatch:
    inputs:
      # Name of the target function without 'aws-lambda-package-' prefix.
      function_name:
        description: 'Function Name'
        required: true
        default: 'skyriseFunctionReadS3'
      # Specify the memory configuration of the function.
      memory_configuration:
        type: choice
        description: 'Memory Allocation'
        required: false
        default: '128'
        options:
          - '128'
          - '1024'
          - '2048'
          - '4096'
          - '10240'
      # Specify the build type (Release or Debug) of the function.
      build_type:
        type: choice
        description: 'Build Type'
        required: true
        default: 'Release'
        options:
          - 'Release'
          - 'Debug'
      # Description, uses the GitHub username if not explicitly provided.
      description:
        description: 'Description'
        required: true
        default: GitHub Username

jobs:
  # Start the Amazon EC2 CI runner.
  start-ec2-instance:
    runs-on: [ self-hosted, amazonlinux2 ]
    name: Start Amazon EC2 Instance
    steps:
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

  # Build the target function on the Amazon EC2 runner and upload it.
  build-arm-function:
    runs-on: [ self-hosted, ARM64, deploy ]
    name: Build and upload function
    needs: start-ec2-instance
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set Description
        run: |
          if [ '${{ inputs.description }}' = 'GitHub Username' ]; then echo "DESCRIPTION=${{ github.actor }}" >> $GITHUB_ENV; \
          else echo "DESCRIPTION=${{ inputs.description }}" >> $GITHUB_ENV; fi;    

      - name: "CMake Configure"
        run: |
          mkdir cmake-build
          cd cmake-build
          cmake .. -GNinja \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -DSKYRISE_ENABLE_CCACHE=OFF \

      - name: "Build ${{ inputs.function_name }}"
        run: |
          cd cmake-build
          ninja-build aws-lambda-package-${{ inputs.function_name }} skyrise -j$(nproc)

      - name: "Upload ${{ inputs.function_name }} to AWS"
        run: |
          cd cmake-build
          ./bin/skyrise -t function-upload -n ${{ inputs.function_name }} -d ${{ env.DESCRIPTION}} -m ${{ inputs.memory_configuration }}

  # Stop the Amazon EC2 instance.
  stop-ec2-instance:
    runs-on: [ self-hosted, amazonlinux2 ]
    name: Stop Amazon EC2 Instance
    if: always()
    needs: [ start-ec2-instance, build-arm-function ]
    steps:
      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
